  var fields = ['PrimaryAttendee.FirstName',
                'PrimaryAttendee.LastName',
                'PrimaryAttendee.Email',
                'PrimaryAttendee.Phone',
                'PrimaryAttendee.Address1',
                'PrimaryAttendee.Address2',
                'PrimaryAttendee.City',
                'PrimaryAttendee.State',
                'PrimaryAttendee.PostalCode',
              ];
